### ISSUE TITLE
Query Error in mod_attendanceregister\task\cron_task

### ISSUE THREAD

**Issue by mciotti** [CinecaElearning/moodle-mod_attendanceregister#10]
We are receiving an error when the 'mod_attendanceregister\task\cron_task' Cron Job is running.
I think the problem is in cronlib.php's function "get_max_users_registers_logouts". I think the field "id" is not needed in the query. Could you correct the file cronlib.php?
Thanks

Here the log:
Execute scheduled task: Ricalcolo sessioni registro presenze (mod_attendanceregister\task\cron_task)
... started 03:18:01. Current memory use 5.3 MB.
... used 240 dbqueries
... used 0.6714870929718 seconds
Scheduled task failed: Ricalcolo sessioni registro presenze (mod_attendanceregister\task\cron_task),Si è verificato un errore durante la lettura del database
Debug info:
ERROR:  column "mdl_attendanceregister_session.id" must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: select id, max(logout) logout, register, userid from mdl_att...
               ^
select id, max(logout) logout, register, userid from mdl_attendanceregister_session group by register, userid
[array (
)]
Backtrace:
* line 293 of /lib/dml/moodle_read_slave_trait.php: call to moodle_database->query_end()
* line 341 of /lib/dml/pgsql_native_moodle_database.php: call to pgsql_native_moodle_database->read_slave_query_end()
* line 1027 of /lib/dml/pgsql_native_moodle_database.php: call to pgsql_native_moodle_database->query_end()
* line 189 of /mod/attendanceregister/cronlib.php: call to pgsql_native_moodle_database->get_records_sql()
* line 50 of /mod/attendanceregister/cronlib.php: call to get_max_users_registers_logouts()
* line 360 of /mod/attendanceregister/lib.php: call to attendanceregister_update_sessions_from_id()
* line 43 of /mod/attendanceregister/classes/task/cron_task.php: call to attendanceregister_cron()
* line 263 of /lib/cronlib.php: call to mod_attendanceregister\task\cron_task->execute()
* line 120 of /lib/cronlib.php: call to cron_run_inner_scheduled_task()
* line 73 of /lib/cronlib.php: call to cron_run_scheduled_tasks()
* line 178 of /admin/cli/cron.php: call to cron_run()

**Comment by CinecaElearning** [comment]
Hello,
we released a patch for this problem.
A note on the side: on mysqli the problem is not detectable due to Moodle sql_mode settings.

**Comment by Pacman20** [comment]
Hi CinecaElearning, I just install the last version but I keep having the problem that the hours are not updated. Do you have any update. 
And thank you for this pluggin, is excellent!
