### ISSUE TITLE
Language strings other than English

### ISSUE THREAD

**Issue by germanvaleroelizondo** [CinecaElearning/moodle-mod_attendanceregister#2]
Hi,

I like your plugin very much, but when I was looking at the description, I found one small issue:

The Attendance Register plugin for Moodle currently has several translations available at AMOS (https://lang.moodle.org) :

French (fr) 
Hungarian (hu)
Norwegian (no) 
Portuguese (Brazil) (pt_br) 
Spanish - Mexico (es_mx)

Plugin authors no longer need to enclose Language strings for languages other than English (eg, italian). I already submitted the Italian language strings to the Italian language pack maintainer; it should be uploaded into the Italian language pack soon.

Please read the developer's documentation about this in https://docs.moodle.org/dev/Plugin_contribution_checklist#Strings

**Comment by CinecaElearning** [comment]
Hi germanvaleroelizondo,
thank you very much for submitting Italian language strings. We will release soon a new minor release to be compliant with last translation moodle rules
Stay tuned ;)

**Comment by germanvaleroelizondo** [comment]
Thank you :)

**Comment by germanvaleroelizondo** [comment]
The Italian language package maintainer (Andrea Bicciolo) has kindly accepted the strings:

"Edited some strings for a better compliance with existing core translation.
Now the strings are part of the Italian language pack, propagated on all branches."

**Comment by CinecaElearning** [comment]
We've just published an updated of the module. Thank you very much for your contribute!!
