### ISSUE TITLE
Create_function should not be used

### ISSUE THREAD

**Issue by 2shediac** [CinecaElearning/moodle-mod_attendanceregister#4]
In locallib.php, create_function is used.

I believe this can be corrected with 

old:
 usort($uniqueTrackedUsers, create_function('$a,$b', $compareByFullName));

new
        usort($uniqueTrackedUsers, function($a, $b) {
          return strcmp( fullname($a), fullname($b) );
        });

**Comment by CinecaElearning** [comment]
Hi, I've just updated the master branch with your patch. Thank you very much!
