### ISSUE TITLE
Error when accessing register from Activities block

### ISSUE THREAD

**Issue by daniel-hefley** [CinecaElearning/moodle-mod_attendanceregister#6]
When clicking on the Attendance Register link located in the Activities block the following error appears:
"Coding error detected, it must be fixed by a programmer: get_all_sections() is removed. See phpdocs for this function"
I am running Moodle version 3.0.9+ with Attendance Register plugin version 2017112200.

This plugin is incredibly useful for our online school. Thanks!

**Comment by CinecaElearning** [comment]
Hi Daniel,
I've just released a new version with a patch.
Thank you very much for your report.
